apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170297138
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170297138
    app.kubernetes.io/part-of: test-app-170297138
  name: java-quarkus-170297138
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170297138
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170297138
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170297138/java-quarkus-170297138@sha256:178304b40fa102e99a2c951de5e32e837ea6c50fc4233c3d265e61567aa563f6
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
