apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-170297138
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/user1-tenant/test-app-170297138/java-quarkus-170297138@sha256:178304b40fa102e99a2c951de5e32e837ea6c50fc4233c3d265e61567aa563f6
        name: my-java-quarkus
        resources: {}
status: {}
